# Generated by Django 4.2.30 on 2026-04-15 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import image_gen.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True, default=' ')),
                ('num_inference_steps', models.PositiveIntegerField(default=40)),
                ('true_cfg_scale', models.FloatField(default=4.0)),
                ('guidance_scale', models.FloatField(default=1.0)),
                ('seed', models.IntegerField(default=0)),
                ('output_width', models.PositiveIntegerField(default=1024)),
                ('output_height', models.PositiveIntegerField(default=1024)),
                ('output_image', models.ImageField(blank=True, null=True, upload_to=image_gen.models.output_image_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('api_key_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='api.apikey')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobInputImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=image_gen.models.input_image_upload_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_images', to='image_gen.generationjob')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
